% a script designed to make surface plots of CSX using data
% generated by the scripts in neoclassical-calculations repository

% simple torus example - comment out the load in line 19 to see
R = 2.0;
r = 0.718;
theta = linspace(0, 2*pi, 37);
phi = linspace(0, 2*pi, 27);
[theta, phi] = meshgrid(theta, phi);
x = R + r*cos(theta);
y = x;
X = x.*cos(phi);
Y = y.*sin(phi);
Z = r*sin(theta);
C = X;
% end of example

% loads file generated by processOutputs.py
load('csxSurface_rN_0.55_Ionflowvelocitykm_s.mat')

colorbarlabel = "Ion flow velocity [km/s]";
annotationtext = ' ';
outputfilename = 'IonFlowVelocityTest.pdf';

% C is the color of the surface, representing the physical quantity
% scale is a parameter sometimes used for units (the python code 
% returns quantities in SI units)
scale = 1/1000;
s = surf(X, Y, Z, C*scale, ...
        'EdgeColor', 'none', ...
        'FaceLighting', 'phong');

cb = colorbar;
cb.FontSize = 16;

% adjust the limits for the colorbar (good for comparing multiple 
% figures, in case you want consistent limits across plots)
% clim([0.005, 0.210])

ylabel(cb, colorbarlabel, "FontSize", 19)

colormap parula
%others: parula, summer, spring, autumn, winter, hot, cool, turbo, hsv
shading interp
lighting phong

% some options for lighting that I ended up not using 

%camlight headlight  % light source from camera
%light('Position', [-2.5 -2.5 4], 'Style', 'infinite');
%light('Position', [-4 0 2], 'Style', 'infinite');
%light('Position', [0.5 -4 2.5], 'Style', 'infinite');

material dull
axis vis3d
axis equal
axis off
box off

annotation('textbox', [0.15, 0.15, 0.3, 0.05], ...
    'String', annotationtext, ...
    'FontSize', 16, ...
    'EdgeColor', 'none');  % no box

% exportgraphics(gcf, 'eflow_0.png', 'Resolution', 300);
exportgraphics(gcf, outputfilename, 'ContentType', 'vector');